---
AWSTemplateFormatVersion: '2010-09-09'
Description: Data Platform EC2 Stack
#Parameters:
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0be2609ba883822ec"
      InstanceType: "t2.micro"
      KeyName: "EC2 Tutorial"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: "InstanceSecurityGroup"
          SubnetId: "subnet-050d3d3573bd8a7f5"
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: "vpc-069114837c1169cca"
#        Ref: Vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0