---
AWSTemplateFormatVersion: '2010-09-09'
# Description
Description: Data Science Redshift stack
# Parameters
Parameters:
  DeploymentName:
    Description: The name of the deployment
    Type: String
  RedshiftPublicSubnetIDAz1:
    Description: Public subnet ID Az1
    Type: String
  RedshiftPublicSubnetIDAz2:
    Description: Public subnet ID Az2
    Type: String
  RedshiftInternalSubnetIDAz1:
    Description: Internal subnet ID Az1
    Type: String
  RedshiftInternalSubnetIDAz2:
    Description: Internal subnet ID Az2
    Type: String
# Resources
Resources:
  # Redshift IAM role for full redshift, redshift spectrum and glue access
  # Redshift subnet group
  RedshiftClusterSubnetGroup:
    Type: AWS::Redshift::ClusterSubnetGroup
    Properties:
      Description: Redshift cluster subnet group
      SubnetIds:
        - !Ref RedshiftPublicSubnetIDAz1
        - !Ref RedshiftPublicSubnetIDAz2
        - !Ref RedshiftInternalSubnetIDAz1
        - !Ref RedshiftInternalSubnetIDAz2
      Tags:
        - Key: DeploymentName
          Value: !Ref DeploymentName
        - Key: Name
          Value: !Sub "${DeploymentName}-dev-redshift"
  # Redshift cluster
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      AllowVersionUpgrade: true
      # Change value once data is in production
      AutomatedSnapshotRetentionPeriod: 0
      AvailabilityZone: us-east-1a
      ClusterIdentifier: oxio-datawarehouse
#      ClusterParameterGroupName: String
#      create security group here and reference
#      ClusterSecurityGroups:
#        - nn-datawarehouse-to-laptopclient
      ClusterSubnetGroupName: !Ref RedshiftClusterSubnetGroup
      ClusterType: single-node
#      ClusterVersion: String
      DBName: dev
#      ElasticIp: String
      # Add encryption in production
#      Encrypted: Boolean
#      HsmClientCertificateIdentifier: String
#      HsmConfigurationIdentifier: String
      IamRoles:
        - arn:aws:iam::208109157855:role/MyNorthVirginiaRedshiftRole
#      KmsKeyId: String
#      LoggingProperties:
#        LoggingProperties
      MasterUsername: awsuser
#      MasterUserPassword:
      NodeType: dc2.large
#      NumberOfNodes: 1
#      OwnerAccount: String
#      Port: 5439
#      PreferredMaintenanceWindow: String
#      PubliclyAccessible: Boolean
#      SnapshotClusterIdentifier: String
#      SnapshotIdentifier: String
      Tags:
        - Key: DeploymentName
          Value: !Ref DeploymentName
        - Key: Name
          Value: !Sub "${DeploymentName}-dev-redshift"#      VpcSecurityGroupIds:
#        - String

